### ISSUE TITLE
unable to create a virtual order

### ISSUE THREAD

**Issue by jkeller92** [netresearch/dhl-module-label-status-m2#3]
With Dhl_LabelStatus installed a virtual order can not be created in checkout.
the function `$carrier = $order->getShippingMethod(true)->getData('carrier_code');` will fail for virtual orders since shipping does not exist.

see PR here
#2

**Comment by powli** [comment]
Hey @jkeller92,

thank you for the contribiution! We'll review it internally and include the fix in the next patch release.

**Comment by powli** [comment]
Fixed in [1.0.1](https://github.com/netresearch/dhl-module-label-status-m2/releases/tag/1.0.1)
