### ISSUE TITLE
dhl label won't be created for paypal express orders

### ISSUE THREAD

**Issue by jkeller92** [netresearch/dhl-module-label-status-m2#4]
Since Paypal does not fire the Event `checkout_submit_all_after` the dhl status label will not be created

See PR here #1

**Comment by powli** [comment]
Hey @jkeller92,

thank you for the contribiution! We'll review it internally and include the fix in the next patch release.

**Comment by powli** [comment]
Fixed in [1.0.1](https://github.com/netresearch/dhl-module-label-status-m2/releases/tag/1.0.1)
