### ISSUE TITLE
Support for PHP7.3

### ISSUE THREAD

**Issue by phoenix-bjoern** [netresearch/dhl-module-label-status-m2#5]
Magento 2.3.4 has support for PHP7.3. When upgrading to PHP7.3 we see the following error:

```Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dhl/module-label-status 1.0.1 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.14) does not satisfy that requirement.
    - dhl/module-label-status 1.0.1 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.14) does not satisfy that requirement.
    - dhl/module-label-status 1.0.1 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.14) does not satisfy that requirement.
    - dhl/module-label-status 1.0.1 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.14) does not satisfy that requirement.
    - Installation request for dhl/module-label-status (locked at 1.0.1, required as *) -> satisfiable by dhl/module-label-status[1.0.1].

```

Please update the PHP version constraint in composer.json to support PHP7.3.

**Comment by mam08ixo** [comment]
[DHL LabelStatus 1.1.0](https://github.com/netresearch/dhl-module-label-status-m2/releases/tag/1.1.0) comes with PHP 7.3 support.

~Please note that _label status_ is a native feature since [DHL Shipping 0.11.0](https://github.com/netresearch/dhl-module-shipping-m2/releases/tag/0.11.0) and does no longer require a separate module.~

_Label Status_ is still a separate module but is required by [DHL Shipping 0.11.0](https://github.com/netresearch/dhl-module-shipping-m2/releases/tag/0.11.0) – no need to add it as project requirement.

**Comment by ngolatka** [comment]
Hello,     please update to Version 1.1.0. It will add the support for PHP 7.3.*     Best regards  Thomas Schöne    Operations Team     www.netresearch.de     Netresearch DTT GmbH  Nonnenstraße 11c - 04229 Leipzig - Germany  Registergericht: AG Leipzig HRB 34690  Geschäftsführer: Dr. Doreen Max, Thomas Wilhelm, Thomas Fleck     DHLSUP-1056093     ------------------      
             
              On
              Mon, 17 Feb at 11:20 PM
              ,  netresearchdhl-module-label-status-m2 <reply@reply.github.com>  wrote:
               Magento 2.3.4 has support for PHP7.3. When upgrading to PHP7.3 we see the following error: 
 
  Problem 1
    - dhl/module-label-status 1.0.1 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.14) does not satisfy that requirement.
    - dhl/module-label-status 1.0.1 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.14) does not satisfy that requirement.
    - dhl/module-label-status 1.0.1 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.14) does not satisfy that requirement.
    - dhl/module-label-status 1.0.1 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.14) does not satisfy that requirement.
    - Installation request for dhl/module-label-status (locked at 1.0.1, required as *) -> satisfiable by dhl/module-label-status[1.0.1].

 
 Please update the PHP version constraint in composer.json to support PHP7.3.
